// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: discovery.proto

package discoveryclient

import (
	"context"

	"discovery/discovery"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = discovery.Request
	Response = discovery.Response

	Discovery interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultDiscovery struct {
		cli zrpc.Client
	}
)

func NewDiscovery(cli zrpc.Client) Discovery {
	return &defaultDiscovery{
		cli: cli,
	}
}

func (m *defaultDiscovery) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := discovery.NewDiscoveryClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
