// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: registration.proto

package server

import (
	"context"

	"registration/internal/logic"
	"registration/internal/svc"
	"registration/registration"
)

type RegistrationServer struct {
	svcCtx *svc.ServiceContext
	registration.UnimplementedRegistrationServer
}

func NewRegistrationServer(svcCtx *svc.ServiceContext) *RegistrationServer {
	return &RegistrationServer{
		svcCtx: svcCtx,
	}
}

func (s *RegistrationServer) Ping(ctx context.Context, in *registration.Request) (*registration.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
