// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: registration.proto

package registrationclient

import (
	"context"

	"registration/registration"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = registration.Request
	Response = registration.Response

	Registration interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRegistration struct {
		cli zrpc.Client
	}
)

func NewRegistration(cli zrpc.Client) Registration {
	return &defaultRegistration{
		cli: cli,
	}
}

func (m *defaultRegistration) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := registration.NewRegistrationClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
