---
# ETCD 部署
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: base
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.15
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: ETCD_NAME
          value: "etcd0"
        - name: ETCD_DATA_DIR
          value: "/etcd-data"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd.base.svc.cluster.local:2379"
        - name: ETCD_LISTEN_PEER_URLS
          value: "http://0.0.0.0:2380"
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: "http://etcd.base.svc.cluster.local:2380"
        - name: ETCD_INITIAL_CLUSTER
          value: "etcd0=http://etcd.base.svc.cluster.local:2380"
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: "etcd-cluster-1"
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: "new"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
        livenessProbe:
          httpGet:
            path: /health
            port: 2379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 2379
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: etcd-data
        emptyDir: {}

---
# ETCD Service - 集群内访问
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: base
  labels:
    app: etcd
spec:
  type: ClusterIP
  ports:
  - port: 2379
    targetPort: 2379
    protocol: TCP
    name: client
  - port: 2380
    targetPort: 2380
    protocol: TCP
    name: peer
  selector:
    app: etcd

---
# ETCD NodePort Service - 外部访问
apiVersion: v1
kind: Service
metadata:
  name: etcd-external
  namespace: base
  labels:
    app: etcd
spec:
  type: NodePort
  ports:
  - port: 2379
    targetPort: 2379
    protocol: TCP
    name: client
    nodePort: 32379
  selector:
    app: etcd
