// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: discovery.proto

package server

import (
	"context"

	"discovery/discovery"
	"discovery/internal/logic"
	"discovery/internal/svc"
)

type DiscoveryServer struct {
	svcCtx *svc.ServiceContext
	discovery.UnimplementedDiscoveryServer
}

func NewDiscoveryServer(svcCtx *svc.ServiceContext) *DiscoveryServer {
	return &DiscoveryServer{
		svcCtx: svcCtx,
	}
}

func (s *DiscoveryServer) Ping(ctx context.Context, in *discovery.Request) (*discovery.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
